### ISSUE TITLE
Bug: Importing text files with a RGB value next to a semicolon that isn't '0' causes import to fail

### ISSUE THREAD

**Issue by AngelHam** [nicolasdeory/LED-AnimationDesigner#10] opened 2020-05-18 02:20 UTC
Came across this issue when trying to put a blue on the last LED light of the Strip, after testing I found this issue also exists with the last LED of the keyboard (the '.' on the numpad).

When I change this value to 0 instead of 215 the import is successful.
![IssueWithBlueValue](https://user-images.githubusercontent.com/60297344/82168020-337a1d00-9883-11ea-9824-a5324aaec0b9.png)

For reference, I cannot import a file that affects the last LED light on the Strip if it has a Blue value (RGB).
![IssueWithBlueValue2](https://user-images.githubusercontent.com/60297344/82168068-57d5f980-9883-11ea-952e-391d7a0ba8c5.png)

**Comment by nicolasdeory** [comment] 2020-07-19 11:31
Fixed in bf5d52a, feel free to reopen if the issue is still present.

**Closed as completed by nicolasdeory** 2020-07-19 11:31 UTC
